const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const express = require('express');
const request = require('supertest');
const jwt = require('jsonwebtoken');
const crypto = require('node:crypto');
const bcrypt = require('bcryptjs');
const { MongoMemoryReplSet } = require('mongodb-memory-server');
const platform = require('../src/tenancy/platform');
const billing = require('../src/services/ownerBilling');
const databases = require('../src/tenancy/connections');
const { gate, runBranch } = require('../src/tenancy/access');
const User = require('../src/models/User');
let mongo, app, school, branch, owner, token, invoice, principalToken, teacherToken;
const password = 'Test-Strong-123!';
const today = billing.today();
const first = `${today.slice(0, 7)}-01`;
const call = (method, path, body, auth = token) => request(app)[method](path).set('Authorization', `Bearer ${auth || ''}`).send(body);
const settings = { erpBaseMinor: 1000000, maintenanceMinMinor: 10000, maintenanceMaxMinor: 50000, freeMonths: 2, taxPercent: 18 };
const payment = (amount, requestId = crypto.randomUUID()) => ({ amountMinor: amount, requestId, method: 'upi', paymentDate: today, reference: 'BANK-REF', notes: '' });
before(async () => {
  process.env.JWT_SECRET = 'test-owner-billing';
  process.env.TENANT_DB_ENCRYPTION_KEY = crypto.randomBytes(32).toString('base64');
  process.env.OWNER_DB_NAME = 'owner_billing_tests';
  mongo = await MongoMemoryReplSet.create({ binary: { version: '7.0.14' }, replSet: { count: 1 } });
  await platform.connect(mongo.getUri());
  owner = await platform.get().Owner.create({ email: 'owner@test.example', name: 'Owner', passwordHash: 'unused' });
  token = jwt.sign({ id: owner._id, role: 'owner', scope: 'owner', version: 0 }, process.env.JWT_SECRET);
  app = express(); app.use(express.json()); app.use('/api/owner', require('../src/routes/ownerRoutes')); app.use('/api', gate);
  app.use('/api/auth', require('../src/routes/authRoutes'));
  app.use('/api/dashboard', require('../src/routes/dashboardRoutes'));
  app.get('/api/probe', (req, res) => res.json({ ok: true }));
  app.use((e, req, res, next) => res.status(e.status || (e.code === 11000 ? 409 : 500)).json({ message: e.message }));
});
after(async () => { await databases.close(); await platform.close(); await mongo?.stop(); });
test('settings validate currency, maintenance range and free months', async () => {
  await call('put', '/api/owner/payment-settings', { ...settings, maintenanceMaxMinor: 1 }).expect(400);
  await call('put', '/api/owner/payment-settings', { ...settings, freeMonths: -1 }).expect(400);
  await call('put', '/api/owner/payment-settings', settings).expect(200);
  const config = (await call('get', '/api/owner/payment-settings').expect(200)).body;
  assert.equal(config.erpBaseMinor, settings.erpBaseMinor);
  const pricing = await billing.pricing({ discountMinor: 100000, monthlyMaintenanceMinor: 20000, cycle: 'quarterly', activationDate: billing.shift(first, -2) });
  assert.equal(pricing.erpNetMinor, 900000);
  assert.equal(pricing.firstMaintenanceDate, first);
  school = await platform.get().School.create({ name: 'Billing School', code: 'billing', pricing });
  branch = await platform.get().Branch.create({ schoolId: school._id, name: 'Main', code: 'main', isMain: true, databaseKey: 'test-billing-db', encryptedUri: databases.encrypt(mongo.getUri('billing_branch')) });
  await platform.get().Principal.create({ schoolId: school._id, email: 'principal@test.example', name: 'Principal', passwordHash: await bcrypt.hash(password, 4) });
  await runBranch(school, branch, async () => { await User.create({ name: 'Teacher', email: 'teacher@test.example', passwordHash: await bcrypt.hash(password, 4), role: 'teacher' }); });
  principalToken = (await call('post', '/api/auth/login', { email: 'principal@test.example', password, schoolCode: school.code }, null).expect(200)).body.token;
  teacherToken = (await call('post', '/api/auth/login', { email: 'teacher@test.example', password, schoolCode: school.code }, null).expect(200)).body.token;
});
test('school pricing snapshots survive global settings changes', async () => {
  await call('put', '/api/owner/payment-settings', { ...settings, erpBaseMinor: 2000000 }).expect(200);
  assert.equal((await platform.get().School.findById(school._id)).pricing.erpBaseMinor, 1000000);
  assert.equal(await platform.get().Invoice.countDocuments(), 0);
  const reminders = (await call('get', '/api/owner/billing-reminders').expect(200)).body;
  assert.equal(reminders.length, 1); assert.equal(reminders[0].periodStart, first); assert.equal(reminders[0].amountMinor, 60000);
});
test('owner issues one ERP invoice with discount, tax and two installments', async () => {
  const path = `/api/owner/schools/${school._id}/invoices`;
  await call('post', path, { amountMinor: 1, description: 'Bypass pricing', dueDate: today }).expect(400);
  const payload = { kind: 'erp', paymentMode: 'split', taxPercent: 18, advanceMinor: 500000, dueDate: today, balanceDueDate: billing.shift(today, 1) };
  const result = await call('post', path, payload).expect(201); invoice = result.body;
  assert.equal(invoice.amountMinor, 1062000); assert.equal(invoice.discountMinor, 100000); assert.equal(invoice.taxMinor, 162000);
  assert.equal(invoice.installments.length, 2); assert.equal(invoice.installments[1].amountMinor, 562000);
  await call('post', path, payload).expect(409);
  await call('post', path, payload, teacherToken).expect(403);
  assert.equal(await platform.get().Mail.countDocuments({ key: new RegExp(`^invoice:${invoice._id}`) }), 2);
  await call('put', `/api/owner/schools/${school._id}/pricing`, { discountMinor: 0, monthlyMaintenanceMinor: 20000, cycle: 'monthly', activationDate: today }).expect(409);
});
test('advance payments allocate in order, are idempotent and reject overpayment', async () => {
  const path = `/api/owner/schools/${school._id}/invoices/${invoice._id}/payments`;
  const body = payment(500000, 'advance');
  const paid = (await call('post', path, body).expect(201)).body;
  assert.equal(paid.status, 'partial'); assert.equal(paid.outstandingMinor, 562000);
  assert.equal(paid.installments[0].outstandingMinor, 0); assert.equal(paid.nextDueDate, billing.shift(today, 1));
  await call('post', path, body).expect(201);
  await call('post', path, { ...body, amountMinor: 1 }).expect(409);
  await call('post', path, payment(562001)).expect(409);
  assert.equal(await platform.get().Payment.countDocuments({ invoiceId: invoice._id }), 1);
  assert.equal(await platform.get().CompletedInvoice.countDocuments({ billId: invoice._id }), 0);
  const ledger = (await call('get', `/api/owner/schools/${school._id}/payments`).expect(200)).body;
  assert.equal(ledger.summary.erpPendingMinor, 562000); assert.equal(ledger.payments.length, 1);
});
test('only an unpaid overdue installment blocks operational access, not principal billing', async () => {
  const oldDue = new Date('2020-01-01');
  await platform.get().Invoice.updateOne({ _id: invoice._id }, { $set: { 'installments.0.dueAt': oldDue } });
  await call('get', '/api/probe', undefined, principalToken).expect(200);
  await platform.get().Invoice.updateOne({ _id: invoice._id }, { $set: { 'installments.1.dueAt': oldDue } });
  await call('get', '/api/probe', undefined, principalToken).expect(402);
  const result = (await call('get', '/api/dashboard/billing', undefined, principalToken).expect(200)).body;
  assert.equal(result.schoolAccess, 'overdue'); assert.equal(result.ledger.summary.overdueMinor, 562000);
  const login = (await call('post', '/api/auth/login', { email: 'principal@test.example', password, schoolCode: school.code }, null).expect(200)).body;
  assert.equal(login.user.schoolAccess, 'overdue');
  const teacher = (await call('get', '/api/probe', undefined, teacherToken).expect(402)).body;
  assert.equal(teacher.message, 'Something went wrong. Please try again later.');
  await call('get', '/api/dashboard/billing', undefined, teacherToken).expect(402);
  const balance = payment(562000, 'final-balance');
  const paymentPath = `/api/owner/schools/${school._id}/invoices/${invoice._id}/payments`;
  await call('post', paymentPath, balance).expect(201);
  await call('post', paymentPath, balance).expect(201);
  const completed = await platform.get().CompletedInvoice.findOne({ billId: invoice._id });
  assert.ok(completed); assert.equal(completed.amountMinor, 1062000); assert.equal(completed.taxMinor, 162000);
  assert.equal(completed.billNumber, invoice.number);
  assert.equal(await platform.get().CompletedInvoice.countDocuments({ billId: invoice._id }), 1);
  const mails = await platform.get().Mail.find({ key: new RegExp(`^completed-invoice:${completed._id}`) });
  assert.deepEqual(mails.map(m => m.to).sort(), ['owner@test.example', 'principal@test.example']);
  assert.ok(mails.every(m => m.text.includes(completed.number) && m.text.includes('Paid in full')));
  const principalLedger = (await call('get', '/api/dashboard/billing', undefined, principalToken).expect(200)).body.ledger;
  assert.equal(principalLedger.completedInvoices[0].number, completed.number);
  assert.equal(Object.hasOwn(principalLedger, 'expenses'), false);
  await call('get', '/api/probe', undefined, principalToken).expect(200);
});
test('maintenance reminders are consumed by owner-issued invoices, never auto-issued', async () => {
  await require('../src/tenancy/billing').generate();
  assert.equal(await platform.get().Invoice.countDocuments(), 1);
  const path = `/api/owner/schools/${school._id}/invoices`;
  const payload = { kind: 'maintenance', periodStart: first, taxPercent: 18, dueDate: today };
  const result = (await call('post', path, payload).expect(201)).body;
  assert.equal(result.amountMinor, 70800); assert.equal(result.periodEnd, new Date(new Date(`${billing.shift(first, 3)}T00:00:00Z`).getTime() - 86400000).toISOString().slice(0, 10));
  assert.equal((await call('get', '/api/owner/billing-reminders').expect(200)).body.length, 0);
  await call('post', path, payload).expect(409);
  const p = `/api/owner/schools/${school._id}/invoices/${result._id}/payments`;
  const responses = await Promise.all([call('post', p, payment(40000)), call('post', p, payment(40000))]);
  assert.deepEqual(responses.map(r => r.status).sort(), [201, 409]);
  assert.equal((await platform.get().Invoice.findById(result._id)).paidMinor, 40000);
});
test('owner disablement keeps billing visible to principals and hides details from teachers', async () => {
  await platform.get().School.updateOne({ _id: school._id }, { active: false });
  await call('get', '/api/probe', undefined, principalToken).expect(403);
  assert.equal((await call('get', '/api/dashboard/billing', undefined, principalToken).expect(200)).body.schoolAccess, 'disabled');
  assert.equal((await call('post', '/api/auth/login', { schoolCode: school.code, email: 'principal@test.example', password }, null).expect(200)).body.user.schoolAccess, 'disabled');
  assert.equal((await call('post', '/api/auth/login', { schoolCode: school.code, email: 'teacher@test.example', password }, null).expect(403)).body.message, 'Something went wrong. Please try again later.');
});
test('fully discounted ERP costs issue a zero-balance invoice and never suspend access', async () => {
  const pricing = await billing.pricing({ discountMinor: 2000000, monthlyMaintenanceMinor: 20000, cycle: 'monthly', activationDate: today });
  const freeSchool = await platform.get().School.create({ name: 'Discounted School', code: 'discounted', pricing });
  const issued = await billing.issue(freeSchool._id, { kind: 'erp', taxPercent: 18, dueDate: today, paymentMode: 'full' }, owner._id);
  assert.equal(issued.amountMinor, 0); assert.equal(issued.status, 'paid'); assert.equal(issued.outstandingMinor, 0); assert.equal(issued.overdue, false);
  assert.equal(await platform.get().CompletedInvoice.countDocuments({ billId: issued._id }), 1);
});
test('owner expense ledger validates transactions, deduplicates retries and preserves void history', async () => {
  const body = { amountMinor: 10000, transactionDate: today, payee: 'Hosting Vendor', category: 'Hosting', description: 'ERP server hosting', method: 'bank_transfer', reference: 'HOST-001', notes: 'Monthly hosting', requestId: 'expense-hosting' };
  await call('post', '/api/owner/expenses', { ...body, amountMinor: -1 }).expect(400);
  await call('post', '/api/owner/expenses', { ...body, transactionDate: '2026-02-30' }).expect(400);
  await call('post', '/api/owner/expenses', { ...body, transactionDate: '2099-01-01' }).expect(400);
  await call('post', '/api/owner/expenses', { ...body, method: 'invalid' }).expect(400);
  await call('post', '/api/owner/expenses', body, teacherToken).expect(403);
  await call('get', '/api/owner/expenses', undefined, principalToken).expect(403);
  await call('get', '/api/owner/finance-report', undefined, principalToken).expect(403);
  await call('get', '/api/owner/completed-invoices', undefined, teacherToken).expect(403);
  const expense = (await call('post', '/api/owner/expenses', body).expect(201)).body;
  assert.equal((await call('post', '/api/owner/expenses', body).expect(201)).body._id, expense._id);
  await call('post', '/api/owner/expenses', { ...body, amountMinor: 20000 }).expect(409);
  await call('post', '/api/owner/expenses', { ...body, requestId: 'expense-salary', category: 'Development', amountMinor: 5000 }).expect(201);
  const query = `?startDate=${today}&endDate=${today}&limit=1`;
  const list = (await call('get', `/api/owner/expenses${query}`).expect(200)).body;
  assert.equal(list.total, 2); assert.equal(list.items.length, 1); assert.equal(list.totalPages, 2);
  const report = (await call('get', `/api/owner/finance-report${query}`).expect(200)).body;
  assert.equal(report.summary.incomeMinor, 1062000);
  assert.equal(report.summary.expenseMinor, 15000);
  assert.equal(report.summary.netMinor, 1047000);
  assert.equal(report.items.length, 1); assert.ok(report.totalPages > 1);
  const bills = (await call('get', `/api/owner/finance-report?type=bill&startDate=${today}&endDate=${today}`).expect(200)).body;
  assert.ok(bills.items.length > 0); assert.ok(bills.items.every(i => i.signedMinor === 0));
  assert.equal(bills.summary.netMinor, 0);
  await call('patch', `/api/owner/expenses/${expense._id}/void`, { reason: '' }).expect(400);
  await call('patch', `/api/owner/expenses/${expense._id}/void`, { reason: 'Duplicate vendor entry' }, teacherToken).expect(403);
  await call('patch', `/api/owner/expenses/${expense._id}/void`, { reason: 'Duplicate vendor entry' }).expect(200);
  await call('patch', `/api/owner/expenses/${expense._id}/void`, { reason: 'Again' }).expect(409);
  const adjusted = (await call('get', `/api/owner/finance-report?type=expense&startDate=${today}&endDate=${today}`).expect(200)).body;
  assert.equal(adjusted.summary.expenseMinor, 5000); assert.equal(adjusted.summary.netMinor, -5000);
  assert.equal(adjusted.items.find(i => i._id === expense._id).signedMinor, 0);
  assert.equal(await platform.get().Expense.countDocuments(), 2);
  await call('get', `/api/owner/finance-report?startDate=${today}&endDate=2000-01-01`).expect(400);
  await call('get', '/api/owner/expenses?limit=5000').expect(400);
});
test('historical paid invoices appear as income without duplicating new completed invoices', async () => {
  const legacy = await platform.get().Invoice.create({ schoolId: school._id, number: 'INV-HISTORICAL', description: 'Historical invoice', amountMinor: 12300, status: 'paid', paidAt: new Date(), dueDate: today, dueAt: billing.dueAt(today), createdBy: owner._id, updatedBy: owner._id });
  let report = (await call('get', `/api/owner/finance-report?type=invoice&startDate=${today}&endDate=${today}`).expect(200)).body;
  assert.equal(report.summary.incomeMinor, 1074300);
  assert.equal(report.items.filter(i => i.number === legacy.number).length, 1);
  await platform.connection().transaction(async session => {
    await require('../src/services/ownerFinance').complete(legacy, school, owner._id, session);
  });
  report = (await call('get', `/api/owner/finance-report?type=invoice&startDate=${today}&endDate=${today}`).expect(200)).body;
  assert.equal(report.summary.incomeMinor, 1074300);
  assert.equal(report.items.filter(i => i.number === legacy.number).length, 0);
});
