const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const express = require('express');
const request = require('supertest');
const crypto = require('node:crypto');
const jwt = require('jsonwebtoken');
const { MongoMemoryReplSet } = require('mongodb-memory-server');
const platform = require('../src/tenancy/platform');
const billing = require('../src/tenancy/billing');
let mongo, app, token, owner, school;
const today = billing.istDate(new Date());
const subscription = { cycle: 'quarterly', cycleAmountMinor: 100000, monthlyMaintenanceMinor: 10000, firstBillingDate: today };
const call = (method, path, body) => request(app)[method](path).set('Authorization', `Bearer ${token}`).send(body);
const payload = () => ({ name: 'New School', code: 'UNIQUE', principalName: 'Admin', principalEmail: 'admin@example.test', principalPassword: 'Strong-password-123', subscription,
  branches: [{ name: 'North', code: 'north', mongoUri: mongo.getUri('north'), isMain: false }, { name: 'Main', code: 'main', mongoUri: mongo.getUri('main'), isMain: true }] });
before(async () => {
  process.env.JWT_SECRET = 'test-billing';
  process.env.TENANT_DB_ENCRYPTION_KEY = crypto.randomBytes(32).toString('base64');
  process.env.OWNER_DB_NAME = 'billing_control';
  mongo = await MongoMemoryReplSet.create({ binary: { version: '7.0.14' }, replSet: { count: 1 } });
  await platform.connect(mongo.getUri());
  owner = await platform.get().Owner.create({ email: 'owner@example.test', name: 'Owner', passwordHash: 'unused' });
  token = jwt.sign({ id: owner._id, role: 'owner', scope: 'owner', version: 0 }, process.env.JWT_SECRET);
  app = express(); app.use(express.json()); app.use('/owner', require('../src/routes/ownerRoutes'));
  app.use((e, req, res, next) => res.status(e.status || (e.code === 11000 ? 409 : 500)).json({ message: e.message }));
});
after(async () => { await require('../src/tenancy/connections').close(); await platform.close(); await mongo?.stop(); });
test('calendar cycle calculations retain month-end anchors and leap days', () => {
  assert.equal(billing.nextDate('2028-01-31', 'monthly', '2028-01-31'), '2028-02-29');
  assert.equal(billing.nextDate('2028-02-29', 'monthly', '2028-01-31'), '2028-03-31');
  assert.equal(billing.nextDate('2028-02-29', 'annually', '2028-02-29'), '2029-02-28');
  assert.equal(billing.nextDate('2026-11-30', 'quarterly', '2026-11-30'), '2027-02-28');
});
test('multi-branch school requires one main branch and independent databases', async () => {
  const bad = payload(); bad.branches[0].isMain = true;
  await call('post', '/owner/schools', bad).expect(400);
  bad.branches.forEach(x => x.isMain = false);
  await call('post', '/owner/schools', bad).expect(400);
  const duplicate = payload(); duplicate.branches[1].mongoUri = duplicate.branches[0].mongoUri;
  await call('post', '/owner/schools', duplicate).expect(409);
  assert.equal(await platform.get().School.countDocuments(), 0);
  const created = await call('post', '/owner/schools', payload());
  assert.equal(created.status, 201, JSON.stringify(created.body));
  school = created.body;
  assert.equal(school.code, 'unique');
  assert.equal(await platform.get().Branch.countDocuments({ schoolId: school._id }), 2);
  assert.equal(await platform.get().Branch.countDocuments({ schoolId: school._id, isMain: true }), 1);
  const dup = payload(); dup.code = ' Unique ';
  const response = await call('post', '/owner/schools', dup).expect(409);
  assert.match(response.body.message, /School code/);
  assert.equal(await platform.get().Mail.countDocuments(), 2);
});
test('workers never issue bills; owner-issued legacy invoices remain compatible', async () => {
  const now = new Date(`${today}T12:00:00+05:30`);
  await Promise.all([billing.generate(now), billing.generate(now)]);
  await billing.generate(now);
  assert.equal(await platform.get().Invoice.countDocuments({ schoolId: school._id }), 0);
  const dueDate = billing.istDate(new Date(now.getTime() + 15 * 86400000));
  const raised = await call('post', `/owner/schools/${school._id}/invoices`, { amountMinor: 130000, description: 'Legacy maintenance', dueDate }).expect(201);
  await platform.get().Invoice.updateOne({ _id: raised.body._id }, { billingDate: today });
  const invoices = await platform.get().Invoice.find({ schoolId: school._id });
  assert.equal(invoices.length, 1);
  const invoice = invoices[0];
  assert.equal(invoice.amountMinor, 130000);
  assert.equal(invoice.dueDate, billing.istDate(new Date(now.getTime() + 15 * 86400000)));
  assert.equal(invoice.dueAt.toISOString(), new Date(`${invoice.dueDate}T23:59:59.999+05:30`).toISOString());
  assert.equal(await platform.get().Mail.countDocuments({ key: new RegExp(`^invoice:${invoice._id}:`) }), 2);
  const updated = await platform.get().School.findById(school._id);
  assert.equal(updated.subscription.nextBillingDate, today);
});
test('overdue and payment notifications are deduplicated; paused schools do not renew', async () => {
  const invoice = await platform.get().Invoice.findOne({ schoolId: school._id });
  const late = new Date(invoice.dueAt.getTime() + 1);
  await billing.generate(late); await billing.generate(late);
  assert.equal(await platform.get().Mail.countDocuments({ key: new RegExp(`^overdue:${invoice._id}:`) }), 2);
  await call('patch', `/owner/schools/${school._id}/invoices/${invoice._id}`, { status: 'paid', paymentReference: 'test' }).expect(200);
  assert.equal(await platform.get().Mail.countDocuments({ key: new RegExp(`^invoice:${invoice._id}:paid:`) }), 2);
  await platform.get().School.updateOne({ _id: school._id }, { active: false });
  await billing.generate(new Date('2030-01-01'));
  assert.equal(await platform.get().Invoice.countDocuments({ schoolId: school._id }), 1);
});
test('subscription validation rejects bad dates and amounts and existing billed periods', async () => {
  const url = `/owner/schools/${school._id}/subscription`;
  await call('put', url, { ...subscription, cycle: 'weekly' }).expect(400);
  await call('put', url, { ...subscription, firstBillingDate: '2027-02-30' }).expect(400);
  await call('put', url, { ...subscription, monthlyMaintenanceMinor: -1 }).expect(400);
  await call('put', url, subscription).expect(409);
  const firstBillingDate = billing.nextDate(today, 'quarterly', today);
  await call('put', url, { ...subscription, cycle: 'annually', firstBillingDate }).expect(200);
  assert.equal((await platform.get().School.findById(school._id)).subscription.cycle, 'annually');
});
test('mail delivery retries failures without losing notifications or exposing SMTP errors', async () => {
  const { Mail } = platform.get();
  await billing.deliver(async () => { throw Error('secret SMTP password'); });
  assert.equal(await Mail.countDocuments({ sentAt: { $ne: null } }), 0);
  assert.equal(await Mail.countDocuments({ lastError: /secret/ }), 0);
  await Mail.updateMany({}, { nextAttemptAt: new Date(0) });
  const sent = [];
  await billing.deliver(async message => sent.push(message));
  assert.equal(sent.length, await Mail.countDocuments());
  await billing.deliver(async () => { throw Error('must not resend'); });
  assert.equal(await Mail.countDocuments({ sentAt: null }), 0);
  assert.ok(sent.some(m => m.to === 'owner@example.test'));
  assert.ok(sent.some(m => m.to === 'admin@example.test'));
  assert.ok(sent.every(m => m.from.name === 'Lavener Holdings' && m.html.includes('Lavener Holdings') && m.attachments.length === 2));
});
