const express = require("express");
const { requireAuth, requireRole, requirePermission } = require("../middleware/auth");
const asyncHandler = require("../middleware/asyncHandler");
const c = require("../controllers/examWorkflowController");
const router = express.Router();
router.use(requireAuth, requireRole("principal", "staff", "teacher", "parent"));
const principal = requireRole("principal");
const examAdmin = [requireRole("principal", "staff"), requirePermission("examinations")];
router.get("/metadata", requireRole("principal", "staff", "teacher"), requirePermission("examinations"), asyncHandler(c.metadata));
router.get("/plans", ...examAdmin, asyncHandler(c.getPlans));
router.put("/plans", ...examAdmin, asyncHandler(c.savePlan));
router.get("/cycles", requirePermission("examinations"), asyncHandler(c.getCycles));
router.post("/cycles", ...examAdmin, asyncHandler(c.saveDatesheet));
router.put("/cycles", ...examAdmin, asyncHandler(c.saveDatesheet));
router.post("/cycles/:id/publish", principal, asyncHandler(c.publishDatesheet));
router.get("/results", requirePermission("examinations"), asyncHandler(c.getResults));
router.put("/results/:id/subjects/:subjectId", requireRole("teacher"), asyncHandler(c.saveMarks));
router.post("/results/:id/approve", requireRole("teacher"), asyncHandler(c.approveResult));
router.post("/results/:id/return", requireRole("principal", "teacher"), asyncHandler(c.returnResult));
router.post("/results/publish", principal, asyncHandler(c.publishResults));
router.post("/results/:id/promote", principal, asyncHandler(c.promote));
module.exports = router;
